<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Admin_file extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_file_model');
    } 

    /*
     * Listing of admin_file
     */
    function index()
    {
        $data['admin_file'] = $this->Admin_file_model->get_all_admin_file();

        $this->load->view('admin_file/index',$data);
    }

    /*
     * Adding a new admin_file
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','max_length[40]');
		$this->form_validation->set_rules('comments','Comments','max_length[60]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'size' => $this->input->post('size'),
				'comments' => $this->input->post('comments'),
            );
            
            $admin_file_id = $this->Admin_file_model->add_admin_file($params);
            redirect('admin_file/index');
        }
        else
        {
            $this->load->view('admin_file/add');
        }
    }  

    /*
     * Editing a admin_file
     */
    function edit($id)
    {   
        // check if the admin_file exists before trying to edit it
        $admin_file = $this->Admin_file_model->get_admin_file($id);
        
        if(isset($admin_file['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','max_length[40]');
			$this->form_validation->set_rules('comments','Comments','max_length[60]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'size' => $this->input->post('size'),
					'comments' => $this->input->post('comments'),
                );

                $this->Admin_file_model->update_admin_file($id,$params);            
                redirect('admin_file/index');
            }
            else
            {   
                $data['admin_file'] = $this->Admin_file_model->get_admin_file($id);
    
                $this->load->view('admin_file/edit',$data);
            }
        }
        else
            show_error('The admin_file you are trying to edit does not exist.');
    } 

    /*
     * Deleting admin_file
     */
    function remove($id)
    {
        $admin_file = $this->Admin_file_model->get_admin_file($id);

        // check if the admin_file exists before trying to delete it
        if(isset($admin_file['id']))
        {
            $this->Admin_file_model->delete_admin_file($id);
            redirect('admin_file/index');
        }
        else
            show_error('The admin_file you are trying to delete does not exist.');
    }
    
}
