<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class File_model extends CI_Model
{
    protected $table ="admin_file";
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get admin_file by id
     */
    function get_admin_file($id)
    {
        return $this->db->get_where($this->table,array('id'=>$id))->row_array();
    }
    
    /*
     * Get all admin_file
     */
    function get_all_file()
    {
        return $this->db->get('admin_file')->result_array();
    }
    
    /*
     * function to add new admin_file
     */
    function add_admin_file($params)
    {
        $this->db->insert('admin_file',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin_file
     */
    function update_admin_file($id,$params)
    {
        $this->db->where('id',$id);
        $response = $this->db->update('admin_file',$params);
        if($response)
        {
            return "admin_file updated successfully";
        }
        else
        {
            return "Error occuring while updating admin_file";
        }
    }
    
    /*
     * function to delete admin_file
     */
    function delete_admin_file($id)
    {
        $response = $this->db->delete('admin_file',array('id'=>$id));
        if($response)
        {
            return "admin_file deleted successfully";
        }
        else
        {
            return "Error occuring while deleting admin_file";
        }
    }
}
