<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Waybill_model extends CI_Model
{
    protected $table ="admin_waybill";
    function __construct()
    {
        parent::__construct();
    }

    public function insert_batch($data)
    {
        return $this->db->insert_batch($this->table,$data);
    }

    public function update_batch($data)
    {
        return $this->db->update_batch($this->table,$data,'id');
    }

    public function get_waybills($filter)
    {
        if(isset($filter['starttime'])){
            $starttime = strtotime($filter['starttime']);
            $starttime = date('Y-m-d H:i:s',$starttime);
            $this->db->where('starttime >=',$starttime);
        }

        if(isset($filter['company']) and is_array($filter['company'])){
            $customer_com = $filter['company'];
            $this->db->where_in('customer_com',$customer_com);
        }


        $this->db->order_by('id','desc');

        $query = $this->db->get($this->table);
        return $query->result_array();
    }


    public function delete($id)
    {
        $this->db->where('id',$id);
        $this->db->delete($this->table);
    }


}
