<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Waybill_model extends CI_Model
{
    protected $table ="admin_waybill";
    function __construct()
    {
        parent::__construct();
    }
}
